const mongoose = require('mongoose');

const productSchema = new mongoose.Schema({
  name: {
    type: String,
    required: [true, 'Please provide a product name'],
    trim: true,
  },
  description: {
    type: String,
    required: true,
  },
  category: {
    type: String,
    required: true,
    enum: [
      'men-clothing',
      'men-shoes',
      'men-accessories',
      'women-clothing',
      'women-shoes',
      'women-accessories',
      'kids-clothing',
      'kids-shoes',
      'kids-accessories',
      'unisex-clothing',
      'unisex-shoes',
      'unisex-accessories',
      'sports-wear',
      'ethnic-wear',
      'formal-wear',
      'casual-wear',
      'seasonal',
      'sale',
    ],
  },
  subcategory: {
    type: String,
    enum: [
      'shirts',
      'pants',
      'dresses',
      'skirts',
      'jackets',
      'hoodies',
      'sweaters',
      'shorts',
      'underwear',
      'socks',
      'sneakers',
      'boots',
      'sandals',
      'formal-shoes',
      'casual-shoes',
      'hats',
      'scarves',
      'belts',
      'bags',
      'sunglasses',
      'watches',
      'jewelry',
      'activewear',
      'swimwear',
      'loungewear',
      'sarees',
      'lehengas',
      'suits',
      'blazers',
      'tuxedos',
    ],
  },
  price: {
    type: Number,
    required: true,
    min: 0,
  },
  originalPrice: {
    type: Number,
    min: 0,
  },
  discount: {
    type: Number,
    default: 0,
    min: 0,
    max: 100,
  },
  stock: {
    type: Number,
    required: true,
    default: 0,
  },
  images: [String],
  thumbnail: String,
  sizes: [String],
  colors: [
    {
      name: String,
      hex: String,
    },
  ],
  material: [String],
  brand: String,
  rating: {
    type: Number,
    default: 0,
    min: 0,
    max: 5,
  },
  reviewCount: {
    type: Number,
    default: 0,
  },
  reviews: [
    {
      user: mongoose.Schema.Types.ObjectId,
      userName: String,
      comment: String,
      rating: Number,
      createdAt: {
        type: Date,
        default: Date.now,
      },
    },
  ],
  tags: [String],
  isFeatured: {
    type: Boolean,
    default: false,
  },
  isNewArrival: {
    type: Boolean,
    default: true,
  },
  isTrending: {
    type: Boolean,
    default: false,
  },
  createdAt: {
    type: Date,
    default: Date.now,
  },
  updatedAt: {
    type: Date,
    default: Date.now,
  },
});

module.exports = mongoose.model('Product', productSchema);
